version: '3'

services:
  votes-api:
    build: ./votes-api
    ports:
      - "8081:8080"
  
  polls-api:
    build: ./polls-api
    ports:
      - "8082:8080"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
