# Use the official Golang image as a base image
FROM golang:1.21

# Set the working directory inside the container
WORKDIR /app

# Copy the go.mod and go.sum files to the working directory
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the code to the working directory
COPY . .

# Expose port 8080 to the outside
EXPOSE 8080

# Command to run the application
CMD ["go", "run", "main.go"]

